apiVersion: v1alpha1
kind: Setting
metadata:
  name: guqing-higan-setting
spec:
  forms:
    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: radio
          name: rss
          label: RSS
          value: true
          attrs:
            icon: rss
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          name: twitter
          label: Twitter
          placeholder: "只需填入 Twitter 用户名即可"
        - $formkit: text
          name: facebook
          label: Facebook
          placeholder: "只需填入 Facebook 用户名即可"
        - $formkit: text
          name: instagram
          label: Instagram
          placeholder: "只需填入 Instagram 用户名即可"
        - $formkit: text
          name: dribbble
          label: Dribbble
          placeholder: "只需填入 Dribbble 用户名即可"
        - $formkit: text
          name: weibo
          label: 微博
          placeholder: "只需填入微博 Id 即可"
        - $formkit: text
          name: email
          label: Email
          placeholder: "只需填入邮箱地址即可"
        - $formkit: text
          name: github
          label: Github
          placeholder: "只需填入 Github 用户名即可"
        - $formkit: text
          name: qq
          label: QQ
          placeholder: "只需填入 QQ 号即可"
        - $formkit: text
          name: telegram
          label: Telegram
          placeholder: "只需填入 Telegram Id 即可"
    - group: styles
      label: 样式
      formSchema:
        - $formkit: select
          name: color_schema
          label: 配色方案
          value: "dark"
          options:
            - label: "暗黑"
              value: "dark"
            - label: "亮色"
              value: "light"
            - label: "白色"
              value: "white"
        - $formkit: select
          name: text_size
          label: 字体大小
          value: "small"
          options:
            - label: "小字体"
              value: "small"
            - label: "常规"
              value: "normal"
            - label: "大字体"
              value: "large"
        - $formkit: attachment
          name: icon
          label: 首页头像
        - $formkit: radio
          name: avatar_circle
          label: 圆形头像
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: avatar_grayout
          label: 开启灰度头像
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: select
          name: post_list_layout
          label: 文章列表布局
          value: "simple-post-list"
          options:
            - label: "简洁列表"
              value: "simple-post-list"
            - label: "多元列表"
              value: "post-list-summary"
        - $formkit: radio
          name: post_title_uppper
          label: 文章标题大写
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: hitokoto
          label: 博客描述开启一言
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: checkbox
          name: footer_menu
          label: 启用底部菜单
          value: true
        - $formkit: code
          name: resume
          if: "$hitokoto===false"
          label: 个人简介
          language: html
          height: 100px
